// <auto-generated />
using System;
using CavisProject.Infrastructures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CavisProject.Infrastructures.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240611204806_SEED3")]
    partial class SEED3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CavisProject.Domain.Entity.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.AppointmentDetail", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "AppointmentId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Duration")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Method", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.MethodDetail", b =>
                {
                    b.Property<Guid?>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SkinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SkinTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MethodId", "SkinId");

                    b.HasIndex("SkinId");

                    b.ToTable("MethodDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PackageDetail", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("PackagePremiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PackagePremiumId");

                    b.HasIndex("PackagePremiumId");

                    b.ToTable("PackageDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PackagePremium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PackagePremiumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PackagePremiums");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalAnalyst", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalAnalysts");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalAnalystDetail", b =>
                {
                    b.Property<Guid?>("SkinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PersonalAnalystId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SkinId", "PersonalAnalystId");

                    b.HasIndex("PersonalAnalystId");

                    b.ToTable("PersonalAnalystDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalImages");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalMethodDetail", b =>
                {
                    b.Property<Guid?>("PersonalAnalystId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PersonalAnalystId", "MethodId");

                    b.HasIndex("MethodId");

                    b.ToTable("PersonalMethodDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ClickMoney")
                        .HasColumnType("float");

                    b.Property<int>("ClicksAmount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid?>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalMoney")
                        .HasColumnType("float");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URLImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("179f7f08-41a7-48c4-a389-0584aaa49ed9"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sản phẩm là sự kết hợp hoàn hảo của ceramide và hyaluronic acid, giúp nhẹ nhàng loại bỏ hết dầu thừa, bụi bẩn và các lớp trang điểm mà không làm khô da, cho da mềm mại, mịn màng hơn. Thành phần ceramide có tác dụng cải thiện rõ nét sắc diện và độ sáng trong của làn da. Nó ngay lập tức mang đến làn da mịn màng, mềm mại, tăng cường lượng collagen tự nhiên trong da, cho làn da săn chắc. Ngoài ra, ceramide còn giúp làm giảm các nếp nhăn sâu, xóa các nếp nhăn mờ nông, cho bề mặt da láng mượt, săn chắc.",
                            IsDeleted = false,
                            Price = 638000.0,
                            ProductCategoryId = new Guid("5e500a0f-e114-4f88-95d1-f1b12fba0654"),
                            ProductName = "Sữa Rửa Mặt Paula’s Choice Cân Bằng Độ Ẩm Da 190ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/sua-rua-mat-paula-s-choice-can-bang-da-190ml-2329.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/paula.jpg?alt=media&token=25b6781b-fb55-4cc6-999d-1944d6533418"
                        },
                        new
                        {
                            Id = new Guid("83aff4ac-c495-4582-8877-1d2fc83eb9cb"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chứa thành phần làm sạch gốc tự nhiên giúp sạch sâu bụi bẩn, bã nhờn và dưỡng da ẩm mịn.",
                            IsDeleted = false,
                            Price = 83000.0,
                            ProductCategoryId = new Guid("5e500a0f-e114-4f88-95d1-f1b12fba0654"),
                            ProductName = "Kem Rửa Mặt Hada Labo Sạch Sâu Dưỡng Ẩm 80g",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/kem-rua-mat-hada-labo-duong-am-toi-uu-80g-4359.html?gad_source=1&gclid=CjwKCAjw65-zBhBkEiwAjrqRMId5JCuqnjMla9hkVGIMUrzwnpV_bVDm3yfaLjmKMnJj6yLlQ6Wq1RoCu10QAvD_BwE",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/hadalabo.png?alt=media&token=3804cc5d-10c7-4ff4-8a71-4ef665bc413c"
                        },
                        new
                        {
                            Id = new Guid("21653406-6211-4f18-b661-a360b581b397"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giúp làm sạch sâu, se khít lỗ chân lông và kiềm dầu hiệu quả mà không làm khô da. Sản phẩm là sự lựa chọn tối ưu dành cho làn da dầu mụn và nhạy cảm, giúp mang lại làn da sạch thoáng, thanh khiết, không còn nỗi lo về mụn và lỗ chân lông được thu nhỏ.",
                            IsDeleted = false,
                            Price = 140000.0,
                            ProductCategoryId = new Guid("5e500a0f-e114-4f88-95d1-f1b12fba0654"),
                            ProductName = "Sữa Rửa Mặt Vichy Dạng Gel Làm Sạch Sâu Da Dầu Mụn 50ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/sua-rua-mat-dang-gel-vichy-lam-sach-sau-cho-da-nhon-mun-50ml-80971.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/vichy.png?alt=media&token=4fbad0f6-a839-43dd-b704-4864cc3e9ba6"
                        },
                        new
                        {
                            Id = new Guid("ef3342b3-e716-4028-b508-f29a1ec87865"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mang lại làn da sạch bóng và mịn màng sau khi rửa mặt, đồng thời hỗ trợ da hô hấp dễ dàng hơn, chuẩn bị tốt hơn cho giai đoạn tái tạo.",
                            IsDeleted = false,
                            Price = 408000.0,
                            ProductCategoryId = new Guid("5e500a0f-e114-4f88-95d1-f1b12fba0654"),
                            ProductName = "Gel Rửa Mặt Eucerin Làm Sạch Dịu Nhẹ Da Nhạy Cảm 200ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/gel-rua-mat-eucerin-tuoi-mat-cho-da-thuong-nhay-cam-200ml-89925.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/eucerin3.jpg?alt=media&token=3a6317da-f045-42d8-917b-825ea52c5fd8"
                        },
                        new
                        {
                            Id = new Guid("44231b57-5715-46e3-bf7b-8fb891b73ccb"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sữa Rửa Mặt Skin1004 Làm Sạch Sâu Cho Da Nhạy Cảm 125ml từ thương hiệu mỹ phẩm Skin1004 của Hàn Quốc là dạng sữa rửa mặt tạo bọt chứa chiết xuất rau má giúp làm sạch da ngăn ngừa mụn và hỗ trợ điều trị mụn. Chứa thành phần tự nhiên dịu nhẹ cho da nên sữa rửa mặt không làm khô da mà còn giữ ẩm cho da. ",
                            IsDeleted = false,
                            Price = 375000.0,
                            ProductCategoryId = new Guid("5e500a0f-e114-4f88-95d1-f1b12fba0654"),
                            ProductName = "Sữa Rửa Mặt Skin1004 Làm Sạch Sâu Cho Da Nhạy Cảm 125ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/sua-rua-mat-chiet-xuat-rau-ma-skin1004-diu-nhe-lam-sach-sau-da-125ml-86169.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/centella3.png?alt=media&token=49d34368-8e90-4165-baca-a774cc354262"
                        },
                        new
                        {
                            Id = new Guid("0e5cce09-cd4b-4681-a56f-56b4c2baec7c"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước Hoa Hồng Thayers với thành phần không chứa cồn (alcohol-free) và công thức độc quyền kết hợp giữa chiết xuất Lô Hội (Aloe Vera) & chiết xuất cây Phỉ (Witch Hazel) không chưng cất sẽ giúp nhẹ nhàng làm sạch da, cân bằng độ pH và dưỡng ẩm, mang lại vẻ sáng mịn tự nhiên và khỏe mạnh cho làn da của bạn.",
                            IsDeleted = false,
                            Price = 264000.0,
                            ProductCategoryId = new Guid("30e2e877-861b-4ae5-8a6b-b2e93a79175e"),
                            ProductName = "Nước Hoa Hồng Thayers Không Cồn Hương Hoa Hồng 355ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/nuoc-hoa-hong-khong-con-thayers-huong-hoa-hong-355ml-3227.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/2thayers.png?alt=media&token=6d12bf7b-6a41-4cdc-bddf-1ccb677f4d93"
                        },
                        new
                        {
                            Id = new Guid("87092517-b5ca-4794-8a9f-33cb8ab2cbfe"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Giúp da mềm mại, tránh cho da không bị mất nước, mang đến cảm giác thoải mái và cho làn da được thông thoáng, thư giãn.",
                            IsDeleted = false,
                            Price = 325000.0,
                            ProductCategoryId = new Guid("30e2e877-861b-4ae5-8a6b-b2e93a79175e"),
                            ProductName = "Nước Hoa Hồng Evoluderm Dành Cho Da Khô Và Nhạy Cảm 500ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/nuoc-hoa-hong-evoluderm-danh-cho-da-kho-va-nhay-cam-500ml-14949.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/2tonique.jpg?alt=media&token=b9c6411d-cfec-44a5-bbfd-341f3697d725"
                        },
                        new
                        {
                            Id = new Guid("aaa3964a-2eb1-4e95-9fe2-ce972a357bd7"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ngây, Nhân Sâm... giúp mang lại công dụng làm giảm mụn thâm, dưỡng ẩm, tẩy da chết, cân bằng độ pH cho da và là bước đệm hoàn hảo để các dưỡng chất thấm sâu vào da tốt nhất",
                            IsDeleted = false,
                            Price = 400000.0,
                            ProductCategoryId = new Guid("30e2e877-861b-4ae5-8a6b-b2e93a79175e"),
                            ProductName = "Nước Hoa Hồng Caryophy Ngừa Mụn Kiềm Dầu Giảm Thâm 300ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/nuoc-hoa-hong-cho-da-mun-caryophy-300ml-78140.html?gad_source=1&gclid=CjwKCAjw65-zBhBkEiwAjrqRMFIk6UKxeIL3HRR1hvVcUaAjCJiMbyuE5tweE_JTxteiOnVqbvEaIRoCgGkQAvD_BwE",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/2caryophy.png?alt=media&token=1f38576d-d99e-44a8-a625-94b23ecdada3"
                        },
                        new
                        {
                            Id = new Guid("85af885a-abb5-454f-8ad8-d15147bba22e"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước hoa hồng Dear, Klairs Supple Preparation Facial Toner sản phẩm tối ưu trong việc làm sạch, cân bằng độ PH và dưỡng ẩm, có kết cấu dạng lỏng nhẹ, trong suốt và không màu, thẩm thấu nhanh chóng vào da. Kết hợp cùng mùi hương thảo mộc vô cùng dễ chịu, hoàn toàn không gây kích ứng hay cảm giác nhờn dính",
                            IsDeleted = false,
                            Price = 409000.0,
                            ProductCategoryId = new Guid("30e2e877-861b-4ae5-8a6b-b2e93a79175e"),
                            ProductName = "Nước Hoa Hồng Klairs Không Mùi Cho Da Nhạy Cảm 180ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/nuoc-hoa-hong-khong-mui-klairs-danh-cho-da-nhay-cam-180ml-65994.html?gad_source=1&gclid=CjwKCAjw65-zBhBkEiwAjrqRMEJSpgovsMtCFQ3MpacrWVHnPjqQ3_KqAoJ_LWQS2Tnz8BNEfLazNxoCj4MQAvD_BwE",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/2klairs-2.jpg?alt=media&token=d74a0e41-5ab2-40dc-b17c-610118bb4f24"
                        },
                        new
                        {
                            Id = new Guid("897ab50d-ebe3-4869-a1b4-d2d7f288fc45"),
                            ClickMoney = 200.0,
                            ClicksAmount = 0,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nước Hoa Hồng Mamonde Rose Water Toner là dòng toner đến từ thương hiệu mỹ phẩm Mamonde của Hàn Quốc, với thành phần chứa 90,97% nước hoa hồng Damask thay vì nước thông thường giúp dưỡng ẩm sâu, cấp nước nhanh chóng, phục hồi làn da khô ráp, thiếu sức sống.",
                            IsDeleted = false,
                            Price = 360000.0,
                            ProductCategoryId = new Guid("30e2e877-861b-4ae5-8a6b-b2e93a79175e"),
                            ProductName = "Toner Mamonde Dưỡng Ẩm, Dịu Nhẹ Da Nhạy Cảm 250ml",
                            SupplierId = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            TotalMoney = 0.0,
                            URL = "https://hasaki.vn/san-pham/nuoc-can-bang-mamonde-duong-am-diu-nhe-cho-da-nhay-cam-250ml-95787.html",
                            URLImage = "https://firebasestorage.googleapis.com/v0/b/cavisproject.appspot.com/o/2mamonde2.jpg?alt=media&token=d6b5de2a-9ba2-4ed8-88f2-93d459bba634"
                        });
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e500a0f-e114-4f88-95d1-f1b12fba0654"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Sữa rửa mặt"
                        },
                        new
                        {
                            Id = new Guid("30e2e877-861b-4ae5-8a6b-b2e93a79175e"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Toner"
                        },
                        new
                        {
                            Id = new Guid("db5d4968-16f9-48c6-ab2b-feef85208d5a"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Kem dưỡng ngày"
                        },
                        new
                        {
                            Id = new Guid("39201e62-9ce1-45cc-9625-ee52babc780d"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Kem chống nắng"
                        },
                        new
                        {
                            Id = new Guid("839dc6d7-4b15-479b-9e01-17b8d3303144"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Nước tẩy trang"
                        },
                        new
                        {
                            Id = new Guid("c45b4c4a-eefe-4295-8110-e9bed75273d9"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Serum"
                        },
                        new
                        {
                            Id = new Guid("005eb795-d06e-4a1a-b828-87fb00b9e919"),
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ProductCategoryName = "Kem dưỡng đêm"
                        });
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.ProductDetail", b =>
                {
                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SkinId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "SkinId");

                    b.HasIndex("SkinId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("179f7f08-41a7-48c4-a389-0584aaa49ed9"),
                            SkinId = new Guid("550ee872-ea09-42a0-b9ac-809890debafb")
                        },
                        new
                        {
                            ProductId = new Guid("179f7f08-41a7-48c4-a389-0584aaa49ed9"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("83aff4ac-c495-4582-8877-1d2fc83eb9cb"),
                            SkinId = new Guid("05ab75d8-622b-4bab-9543-ad10e441d7d6")
                        },
                        new
                        {
                            ProductId = new Guid("83aff4ac-c495-4582-8877-1d2fc83eb9cb"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("21653406-6211-4f18-b661-a360b581b397"),
                            SkinId = new Guid("90a11b66-e89f-45ab-bfc4-b31101d0dd81")
                        },
                        new
                        {
                            ProductId = new Guid("21653406-6211-4f18-b661-a360b581b397"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("ef3342b3-e716-4028-b508-f29a1ec87865"),
                            SkinId = new Guid("be37023d-6a58-4b4b-92e5-39dcece45473")
                        },
                        new
                        {
                            ProductId = new Guid("ef3342b3-e716-4028-b508-f29a1ec87865"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("44231b57-5715-46e3-bf7b-8fb891b73ccb"),
                            SkinId = new Guid("a960d28f-2807-4d58-8248-91eec518d415")
                        },
                        new
                        {
                            ProductId = new Guid("44231b57-5715-46e3-bf7b-8fb891b73ccb"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("0e5cce09-cd4b-4681-a56f-56b4c2baec7c"),
                            SkinId = new Guid("550ee872-ea09-42a0-b9ac-809890debafb")
                        },
                        new
                        {
                            ProductId = new Guid("0e5cce09-cd4b-4681-a56f-56b4c2baec7c"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("87092517-b5ca-4794-8a9f-33cb8ab2cbfe"),
                            SkinId = new Guid("05ab75d8-622b-4bab-9543-ad10e441d7d6")
                        },
                        new
                        {
                            ProductId = new Guid("87092517-b5ca-4794-8a9f-33cb8ab2cbfe"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("aaa3964a-2eb1-4e95-9fe2-ce972a357bd7"),
                            SkinId = new Guid("90a11b66-e89f-45ab-bfc4-b31101d0dd81")
                        },
                        new
                        {
                            ProductId = new Guid("aaa3964a-2eb1-4e95-9fe2-ce972a357bd7"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("85af885a-abb5-454f-8ad8-d15147bba22e"),
                            SkinId = new Guid("be37023d-6a58-4b4b-92e5-39dcece45473")
                        },
                        new
                        {
                            ProductId = new Guid("85af885a-abb5-454f-8ad8-d15147bba22e"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        },
                        new
                        {
                            ProductId = new Guid("897ab50d-ebe3-4869-a1b4-d2d7f288fc45"),
                            SkinId = new Guid("a960d28f-2807-4d58-8248-91eec518d415")
                        },
                        new
                        {
                            ProductId = new Guid("897ab50d-ebe3-4869-a1b4-d2d7f288fc45"),
                            SkinId = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f")
                        });
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Skin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Category")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkinsName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550ee872-ea09-42a0-b9ac-809890debafb"),
                            Category = true,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2566),
                            Description = "Da cân bằng với vẻ ngoài khỏe mạnh, không quá nhờn cũng không quá khô, và ít khuyết điểm.",
                            IsDeleted = false,
                            SkinsName = "Da thường"
                        },
                        new
                        {
                            Id = new Guid("be37023d-6a58-4b4b-92e5-39dcece45473"),
                            Category = true,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2589),
                            Description = "Sự kết hợp của các loại da; thường thì vùng chữ T (trán, mũi, và cằm) là da nhờn trong khi má là da khô hoặc bình thường.",
                            IsDeleted = false,
                            SkinsName = "Da hỗn hợp"
                        },
                        new
                        {
                            Id = new Guid("a960d28f-2807-4d58-8248-91eec518d415"),
                            Category = true,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2595),
                            Description = "Da dễ phản ứng với các sản phẩm và yếu tố môi trường, thường dẫn đến đỏ, ngứa, hoặc kích ứng.",
                            IsDeleted = false,
                            SkinsName = "Da nhạy cảm"
                        },
                        new
                        {
                            Id = new Guid("05ab75d8-622b-4bab-9543-ad10e441d7d6"),
                            Category = true,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2598),
                            Description = "Da thiếu độ ẩm, thường cảm thấy căng, thô ráp, hoặc bong tróc, và có thể trông xỉn màu.",
                            IsDeleted = false,
                            SkinsName = "Da khô"
                        },
                        new
                        {
                            Id = new Guid("90a11b66-e89f-45ab-bfc4-b31101d0dd81"),
                            Category = true,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2600),
                            Description = "Da sản xuất quá nhiều bã nhờn, dẫn đến vẻ ngoài bóng và có khả năng cao bị mụn và lỗ chân lông to.",
                            IsDeleted = false,
                            SkinsName = "Da nhờn"
                        },
                        new
                        {
                            Id = new Guid("e8685143-0f2e-42fa-8025-da53e1707461"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2604),
                            Description = "Mụn đầu đen là loại mụn mà lỗ chân lông bị tắc bởi bã nhờn và tế bào da chết. Chúng thường màu đen hoặc vàng nâu.",
                            IsDeleted = false,
                            SkinsName = "Mụn đầu đen"
                        },
                        new
                        {
                            Id = new Guid("73766ff0-d528-4262-a1e8-656b33f58603"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2606),
                            Description = "Mụn đầu trắng cũng là lỗ chân lông bị tắc, nhưng bề mặt của chúng bị phủ bởi một lớp da sạch. Chúng thường xuất hiện màu trắng hoặc da, thường nhỏ hơn mụn đầu đen.",
                            IsDeleted = false,
                            SkinsName = "Mụn đầu trắng"
                        },
                        new
                        {
                            Id = new Guid("5ab57d24-20ad-4b15-8427-c951419da3ba"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2609),
                            Description = "Mụn bọc là các nốt sưng và đỏ trên da mà không có đầu trắng hoặc đen ở phần trên. Chúng có thể gây đau và khó chịu.",
                            IsDeleted = false,
                            SkinsName = "Mụn bọc"
                        },
                        new
                        {
                            Id = new Guid("bd287628-2eb7-458a-b202-d89d63faaebf"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2612),
                            Description = "Mụn mủ là các nốt sưng và đỏ có chứa mủ ở phần trên. Chúng thường là dấu hiệu của một nhiễm trùng nặng hơn trong lỗ chân lông.",
                            IsDeleted = false,
                            SkinsName = "Mụn mủ"
                        },
                        new
                        {
                            Id = new Guid("12774b27-0e13-4f82-87d0-bfd6bd23e6e5"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2614),
                            Description = "Mụn viêm đỏ là các nốt sưng lớn và đau nhức dưới da. Chúng thường không có mủ ở phần trên như mụn mủ.",
                            IsDeleted = false,
                            SkinsName = "Mụn viêm đỏ"
                        },
                        new
                        {
                            Id = new Guid("f49b6287-8f31-4fd5-9899-ed1eb6d0564a"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2616),
                            Description = "Mụn đầu đinh là các nốt sưng lớn và đau nhức có mủ ở phần trên. Chúng có thể gây ra tổn thương và vết sẹo nếu không được điều trị đúng cách.",
                            IsDeleted = false,
                            SkinsName = "Mụn đầu đinh"
                        },
                        new
                        {
                            Id = new Guid("a9035561-1399-464f-9f09-38c164a40a63"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2619),
                            Description = "Mụn thâm là các vết sẹo hoặc vết đỏ hoặc nâu trên da sau khi mụn đã lành. Chúng có thể gây ra tự ti và không tự tin về da mặt.",
                            IsDeleted = false,
                            SkinsName = "Mụn thâm"
                        },
                        new
                        {
                            Id = new Guid("8d9526b4-4532-4aff-8f69-379dbac8a55f"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2621),
                            Description = "Nám da là sự xuất hiện của các vùng sạm màu trên da, thường là do tác động của tia UV từ ánh nắng mặt trời.",
                            IsDeleted = false,
                            SkinsName = "Nám da"
                        },
                        new
                        {
                            Id = new Guid("4678f8d2-5648-4521-9608-8e981dee9103"),
                            Category = false,
                            CreationDate = new DateTime(2024, 6, 12, 3, 48, 6, 279, DateTimeKind.Local).AddTicks(2625),
                            Description = "Sự xuất hiện của nếp nhăn trên da thường là kết quả của quá trình lão hóa tự nhiên, nhưng cũng có thể được tăng cường bởi tác động từ môi trường, chế độ ăn uống và lối sống.",
                            IsDeleted = false,
                            SkinsName = "Nếp nhăn"
                        });
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f78562c-4da1-4cf4-9100-22215c0b6530"),
                            Address = "71 Hoàng Hoa Thám, P.13, Q.Tân Bình, TP.HCM",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hotro@hasaki.vn",
                            IsDeleted = false,
                            PhoneNumber = "1800 6324",
                            Status = 1,
                            SupplierName = "Hasaki"
                        });
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeleteBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PackagePremiumId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PurchaseTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalPaid")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PackagePremiumId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBird")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ExpireOTPEmail")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OTPEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<double?>("RewardPoint")
                        .HasColumnType("float");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("Wallet")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.WishList", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.AppointmentDetail", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Appointment", "Appointment")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany("AppointmentDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Calendar", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Method", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.MethodDetail", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Method", "Method")
                        .WithMany("MethodDetails")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.Skin", "Skins")
                        .WithMany("MethodDetails")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Skins");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PackageDetail", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.PackagePremium", "PackagePremium")
                        .WithMany("PackageDetails")
                        .HasForeignKey("PackagePremiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany("PackageDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackagePremium");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalAnalyst", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany("PersonalAnalysts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalAnalystDetail", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.PersonalAnalyst", "PersonalAnalyst")
                        .WithMany("PersonalAnalystDetails")
                        .HasForeignKey("PersonalAnalystId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.Skin", "Skins")
                        .WithMany("PersonalAnalystDetails")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAnalyst");

                    b.Navigation("Skins");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalImage", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalMethodDetail", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Method", "Method")
                        .WithMany("PersonalMethodDetails")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.PersonalAnalyst", "PersonalAnalyst")
                        .WithMany("PersonalMethodDetails")
                        .HasForeignKey("PersonalAnalystId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("PersonalAnalyst");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Product", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId");

                    b.HasOne("CavisProject.Domain.Entity.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");

                    b.Navigation("ProductCategory");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.ProductDetail", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.Skin", "Skins")
                        .WithMany("ProductDetails")
                        .HasForeignKey("SkinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Skins");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.RefreshToken", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany("RefreshToken")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Transaction", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Appointment", "Appointment")
                        .WithMany("Transaction")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.PackagePremium", "PackagePremium")
                        .WithMany("Transactions")
                        .HasForeignKey("PackagePremiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId");

                    b.Navigation("Appointment");

                    b.Navigation("PackagePremium");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.WishList", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Product", "Product")
                        .WithMany("WishLists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.User", "User")
                        .WithMany("WishLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CavisProject.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CavisProject.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Appointment", b =>
                {
                    b.Navigation("AppointmentDetails");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Method", b =>
                {
                    b.Navigation("MethodDetails");

                    b.Navigation("PersonalMethodDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PackagePremium", b =>
                {
                    b.Navigation("PackageDetails");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.PersonalAnalyst", b =>
                {
                    b.Navigation("PersonalAnalystDetails");

                    b.Navigation("PersonalMethodDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Product", b =>
                {
                    b.Navigation("ProductDetails");

                    b.Navigation("WishLists");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Skin", b =>
                {
                    b.Navigation("MethodDetails");

                    b.Navigation("PersonalAnalystDetails");

                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CavisProject.Domain.Entity.User", b =>
                {
                    b.Navigation("AppointmentDetails");

                    b.Navigation("PackageDetails");

                    b.Navigation("PersonalAnalysts");

                    b.Navigation("RefreshToken");

                    b.Navigation("Transactions");

                    b.Navigation("WishLists");
                });
#pragma warning restore 612, 618
        }
    }
}
